### ISSUE TITLE
Problem with mixin --paper-card-header-image and media queries

### ISSUE THREAD

**Issue by marconi1992** [PolymerElements/paper-card#26]
I changed the content-fit from the header image  inside the card to adjust the content depending of the viewport width, I put the mixin --paper-card-header-image inside of the media query but is applied always. 
I know is necessary call the method this.updateStyles() to update the elements on the page, therefore i must create a match media listener to call this.updateStyles().
My simple and reusable solution was fork the repository and add several style class in the paper-card.html, I think  is necessary the adding the properties to create an adjustable header image in next updates.

**Comment by notwaldorf** [comment]
I'm not sure I understand what the issue is, and how you fixed it. Do you have a jsbin or a snippet of code to repro this, or a link to how you fixed it?

**Comment by marconi1992** [comment]
Sorry I wrote wrong the issue, the real issue is that the  style  inside the -paper-card-image-header  is applied always whether  the media query is true or false. The paper-card style works well.
```css
@media screen and (max-width:520px){
      :host paper-card{
        width:100%;
        display:block;
        --paper-card-header-image:{
           height:200px;
           object-fit: cover;
           
        };
      }
    }
```
http://jsbin.com/xiwiko/edit?html,output
